hydra:
  run:
    dir: runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S} # runs/RBC_noquad/2024-12-30/16-12-39 #    

defaults:
  - constants:  RBC_noquad
  - net:        RBC_noquad
  - optimizer:  RBC_noquad
  - run:        RBC_noquad
  - variables:  RBC_noquad
seed: 42 #42
# can be NEW, LATEST, or a given checkpoint filename
STARTING_POINT: LATEST
CHECKPOINT_INTERVAL: 2
MAX_TO_KEEP_NUMBER: 10
MODEL_NAME:     RBC_noquad
#False-> Simulation; True -> draw
initialize_each_episode: True
error_filename: error_file.txt
enable_check_numerics: False