hydra:
  run:
    dir: runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    #runs/RBC_noquad/2024-12-26/16-07-19
    # 
    # runs/RBC_noquad/2024-12-26/XX-XX-XX
    # runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    #runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    #runs/bm1972/2024-11-17/07-51-09
    #runs/bm1972/2024-11-18/17-18-02
    #runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S} # runs/bm1972/2024-11-18/20-08-02
            # runs/bm1972/2024-09-03/13-13-03
    #dir: runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S} #
    #dir: 
    #dir: ../../../../OUTPUT_HYDRA/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
  - constants: RBC_noquad_trad
  - net: RBC_noquad_trad
  - optimizer: RBC_noquad_trad
  - run: RBC_noquad_trad
  - variables: RBC_noquad_trad
seed: 42 #42
# can be NEW, LATEST, or a given checkpoint filename
STARTING_POINT: LATEST
CHECKPOINT_INTERVAL: 2
MAX_TO_KEEP_NUMBER: 10
MODEL_NAME: RBC_noquad_trad
#False-> Simulation; True -> draw
initialize_each_episode: True
error_filename: error_file.txt
enable_check_numerics: False