hydra:
  run:
    dir: runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S} # runs/RBC_nolab_det/2024-12-27/13-47-33 # 
    #dir: ../../../../OUTPUT_HYDRA/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
  - constants: RBC_nolab_det
  - net: RBC_nolab_det
  - optimizer: RBC_nolab_det
  - run: RBC_nolab_det
  - variables: RBC_nolab_det
seed: 42 #42
# can be NEW, LATEST, or a given checkpoint filename
STARTING_POINT: LATEST
CHECKPOINT_INTERVAL: 2
MAX_TO_KEEP_NUMBER: 10
MODEL_NAME: RBC_nolab_det
#False-> Simulation; True -> draw
initialize_each_episode: True
error_filename: error_file.txt
enable_check_numerics: False