layers:
  - hidden:
      units: 25
      type: dense
      activation: softplus
      init_scale: 1
  - hidden:
      units: 25
      type: dense
      activation: softplus
      init_scale: 1
  - output:
      type: dense
      activation: sigmoid
      init_scale: 0.1
