layers:
  - hidden:
      units: 50
      type: dense
      activation: softplus
      init_scale: 0.5
  - hidden:
      units: 50
      type: dense
      activation: softplus
      init_scale: 0.5

  - output:
      type: dense
      activation: linear
      init_scale: 0.25